name: Push dictionaries to OpenNeuro-JSONLD

on:
  push:
    branches:
      - main
      - add_automation
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and submit data dictionaries
        id: get_datasets
        run: |
          for dict in *.json; do
            dataset_name=$(basename $dict .json)

            echo "Beginning upload for ${dataset_name}"
            
            # Attempt to upload the data dictionary with boilerplate information
            response=$(curl --silent --retry 3 --retry-delay 30 \
              -X 'PUT' \
              "https://upload.neurobagel.org/openneuro/upload?dataset_id=${dataset_name}" \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F "data_dictionary=@${dict};type=application/json" \
              -F 'changes_summary=Automatic upload from https://github.com/neurobagel/openneuro-annotations' \
              -F 'name=Bot' \
              -F 'email=bot@neurobagel.org' \
              -F 'affiliation=neurobagel' \
              -F 'gh_username=neurobagel-bot')

            # Check the status of the response
            if echo $response | jq -e 'has("error")' > /dev/null; then
              error_message=$(echo "$response" | jq -r '.error')

              if [[ "$error_message" =~ "same as in the target file." ]]; then
                # Nothing to do
                echo "No changes to upload for ${dataset_name}"
              elif [[ "$error_message" == "404: Not Found. Please ensure you have provided a correct existing dataset ID." ]]; then
                # Repo moved
                echo "Repo ${dataset_name} no longer exists"
              elif [[ "$error_message" == "Something went wrong" ]]; then
                # Other error
                echo "Error uploading ${dataset_name}"
              else
                # Unknown error
                echo "Unknown error: $error_message"
              fi
            elif echo $response | jq -e 'has("pull_request_url")' > /dev/null; then
              # PR opened
              pr_url=$(echo "$response" | jq -r '.pull_request_url')
              echo "PR opened for ${dataset_name}: ${pr_url}"
            else
              # Bad stuff
              echo "Unknown response: $response"
            fi

            echo "Upload completed for ${dataset_name}"

          done

          # We want:
          # - a counter for each outcome level (success, nothing to do, repo gone, new data dictionary)
          # - a list of PRs that were opened
          # - a list of repos that no longer exist

          # {"error":"The content selected for upload is the same as in the target file.","message":"Failed to upload the file to OpenNeuroDatasets-JSONLD."}
          # {"error":"404: Not Found. Please ensure you have provided a correct existing dataset ID.","message":"Failed to upload the file to OpenNeuroDatasets-JSONLD."}
          # {"pull_request_url":"https://github.com/OpenNeuroDatasets-JSONLD/ds003340/pull/1","message":"Successfully uploaded file to OpenNeuroDatasets-JSONLD.","warnings":["The uploaded data dictionary may contain changes that are not related to Neurobagel annotations."]}
