name: Push dictionaries to OpenNeuro-JSONLD

on:
  push:
    branches:
      - main
      - add_automation
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and submit data dictionaries
        id: get_datasets
        run: |
          dataset_names='['
          for dict in $(ls *.json); do
            dataset_name=$(basename "$dict" .json)  

            echo "Beginning upload for ${dataset_name}"
            
            # Attempt to upload the data dictionary with boilerplate information
            response=$(curl --write-out "%{http_code}" --silent --output /dev/null --retry 3 --retry-delay 30 \
              -X 'PUT' \
              "https://upload.neurobagel.org/openneuro/upload?dataset_id=${dataset_name}" \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F "data_dictionary=@${dict};type=application/json" \
              -F 'changes_summary=Automatic upload from https://github.com/neurobagel/openneuro-annotations' \
              -F 'name=Bot' \
              -F 'email=bot@neurobagel.org' \
              -F 'affiliation=neurobagel' \
              -F 'gh_username=neurobagel-bot')

            # Check if the response code indicates success
            if [ "$response" -ne 200 ]; then
              echo "Upload failed for ${dataset_name} with response code $response"
              exit 1
            fi

            echo "Upload completed for ${dataset_name}"

          done