name: Push dictionaries to OpenNeuro-JSONLD

on:
  push:
    branches:
      - main
      - add_automation
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and submit data dictionaries
        id: get_datasets
        run: |
          success_count=0
          fail_count=0
          missing_repos=""
          opened_prs=""

          for dict in *.json; do
            dataset_name=$(basename $dict .json)
            
            # Attempt to upload the data dictionary with boilerplate information
            response=$(curl --silent --retry 3 --retry-delay 30 \
              -X 'PUT' \
              "https://upload.neurobagel.org/openneuro/upload?dataset_id=${dataset_name}" \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F "data_dictionary=@${dict};type=application/json" \
              -F 'changes_summary=Automatic upload from https://github.com/neurobagel/openneuro-annotations' \
              -F 'name=Bot' \
              -F 'email=bot@neurobagel.org' \
              -F 'affiliation=neurobagel' \
              -F 'gh_username=neurobagel-bot')

            # Check the status of the response
            if echo $response | jq -e 'has("error")' > /dev/null; then
              fail_count=$((fail_count + 1))
              error_message=$(echo "$response" | jq -r '.error')

              if [[ "$error_message" =~ "same as in the target file." ]]; then
                # Nothing to do
                echo "${dataset_name}: ${error_message}"
                continue
              elif [[ "$error_message" == "404: Not Found. Please ensure you have provided a correct existing dataset ID." ]]; then
                # Repo moved
                missing_repos="${missing_repos}${dataset_name}\n"
                echo "${dataset_name}: ${error_message}"
                continue
              elif [[ "$error_message" == "Something went wrong" ]]; then
                # Other error
                echo "${dataset_name}: ${error_message}"
                continue
              else
                # Unknown error
                echo "${dataset_name}: ${error_message}"
                continue
              fi
            elif echo $response | jq -e 'has("pull_request_url")' > /dev/null; then
              # PR opened  
              pr_url=$(echo "$response" | jq -r '.pull_request_url')
              success_count=$((success_count + 1))
              opened_prs="${opened_prs}${dataset_name}: ${pr_url}\n"
              echo "${dataset_name}: upload successful - ${pr_url}"
            else
              # Bad stuff
              echo "Unknown response: $response"
              continue
            fi

          done

          echo "Missing repositories:\n${missing_repos}"
          echo "Opened PRs:\n${opened_prs}"
          echo "Success count: ${success_count}"
          echo "Fail count: ${fail_count}"

