name: Push dictionaries to OpenNeuro-JSONLD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.NB_BOT_ID }}
          private-key: ${{ secrets.NB_BOT_KEY }}
          owner: OpenNeuroDatasets-JSONLD

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Find and submit data dictionaries
        id: get_dictionaries
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |

          # Get the list of dictionaries
          data_dictionaries=$(ls *.json)
          n_dictionaries=$(echo "$data_dictionaries" | wc -l)

          # Storage vars
          success_count=0
          fail_count=0
          missing_repos=""
          opened_prs=""
          failed_merge_prs=""

          index=0
          for dict in ${data_dictionaries}; do
            index=$((index + 1))
            dataset_name=$(basename $dict .json)
            
            # Attempt to upload the data dictionary with boilerplate information
            response=$(curl --silent --retry 3 --retry-delay 30 \
              -X 'PUT' \
              "https://upload.neurobagel.org/openneuro/upload?dataset_id=${dataset_name}" \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F "data_dictionary=@${dict};type=application/json" \
              -F 'changes_summary=Automatic upload from https://github.com/neurobagel/openneuro-annotations' \
              -F 'name=Neurobagel Bot' \
              -F 'email=neurobagel-bot[bot]@users.noreply.github.com' \
              -F 'affiliation=neurobagel' \
              -F 'gh_username=neurobagel-bot')

            # Check the status of the response
            if echo "$response" | jq -e 'has("error")' > /dev/null; then
              # The upload API will return an informative error message if the upload failed
              error_message=$(echo "$response" | jq -r '.error')

              if [[ "$error_message" =~ "same as in the target file." ]]; then
                # Nothing to do
                success_count=$((success_count + 1))
              elif [[ "$error_message" == "404: Not Found. Please ensure you have provided a correct existing dataset ID." ]]; then
                # Repo moved
                fail_count=$((fail_count + 1))
                missing_repos="${missing_repos}${dataset_name}\n"
              else
                fail_count=$((fail_count + 1))
              fi
              echo "(${index}/${n_dictionaries}) ${dataset_name}: ${error_message}"
            elif echo "$response" | jq -e 'has("pull_request_url")' > /dev/null; then
              # PR opened
              pr_url=$(echo "$response" | jq -r '.pull_request_url')
              success_count=$((success_count + 1))
              opened_prs="${opened_prs}${dataset_name}: ${pr_url}\n"
              echo "(${index}/${n_dictionaries}) ${dataset_name}: PR opened successfully - ${pr_url}"

              # Reattempt the merge in case the PR mergeability computation isn't complete yet
              # (see https://github.com/cli/cli/issues/8092)
              merged=false
              for i in {1..3}; do:
                if gh pr merge "$pr_url" --squash --delete-branch; then
                  merged=true
                  echo "(${index}/${n_dictionaries}) ${dataset_name}: Successfully merged PR ${pr_url}"
                  break
                fi
                sleep 2
              done
              if [ "$merged" = false ]; then
                failed_merge_prs="${failed_merge_prs}${dataset_name}: ${pr_url}\n"
                echo "(${index}/${n_dictionaries}) ${dataset_name}: Failed to merge PR after 3 attempts: ${pr_url}"
              fi
            else
              # Bad stuff happened and we don't know why
              fail_count=$((fail_count + 1))
              echo "(${index}/${n_dictionaries}) ${dataset_name}: Unknown response: $response"
            fi

          done

          opened_prs_count=$(echo -e "$opened_prs" | grep -c .)
          failed_merge_prs_count=$(echo -e "$failed_merge_prs" | grep -c .)

          echo -e "Missing repositories:\n${missing_repos}"
          echo -e "Num. successfully processed dictionaries: ${success_count}"
          echo -e "Num. dictionaries that failed processing: ${fail_count}"
          echo -e "Opened ${opened_prs_count} PRs:\n${opened_prs}"
          echo -e "Failed to merge ${failed_merge_prs_count} PRs:\n${failed_merge_prs}"
