name: Process all OpenNeuroDerivatives repos

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  get-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find repos
        run: ./code/find_openneuro.sh OpenNeuroDerivatives ./openneuro-derivatives.tsv

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Show repos
        run: cat openneuro-derivatives.tsv
