name: Process all OpenNeuroDerivatives repos

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find repos
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./code/find_openneuro.sh OpenNeuroDerivatives ./openneuro-derivatives.tsv

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt

      - name: Show repos
        run: cat openneuro-derivatives.tsv

      - name: Generate a Neurobagel Bot token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.NB_BOT_ID }}
          private-key: ${{ secrets.NB_BOT_KEY }}

      - name: Get Neurobagel Bot App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Process repos
        env:
          NB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          while IFS=$'\t' read -r repo_name repo_url || [ -n "$repo_name" ]; do
            echo "Processing: $repo_name"
            python ./code/build_repo_map.py "$repo_name" ./repo_derivatives_map.json
          done < ./openneuro-derivatives.tsv

      - name: Configure git for Neurobagel Bot user
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add repo_derivatives_map.json
          git commit -m "[bot] Update repo_derivatives_map.json" || true
          git push origin main
